name: project_221000090
description: A new Flutter pr
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  go_router: ^6.0.9
  cloud_firestore: ^4.5.3
  firebase_auth: ^4.5.0
  firebase_core: ^2.6.1
  provider: ^6.0.5
  firebase_ui_auth: ^1.1.13
  google_sign_in: ^6.1.0
  shrine_images: ^2.0.2
  image_picker: ^0.8.7+5
  firebase_storage: ^11.1.2
  calendar_view: ^1.0.3
  syncfusion_flutter_calendar: ^21.2.3
  google_maps_flutter_android: ^2.4.15

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:
 
  uses-material-design: true
  assets:
    - assets/logo.png 
  