// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
//  import 'firebase_options.dart';
// / // ...
//  await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFClyrfx2eXtBmdKeasq4vB14FZam-Cqw',
    appId: '1:177508526111:web:46d5671583f42c68eecd2a',
    messagingSenderId: '177508526111',
    projectId: 'mobileapp-project-d7c42',
    authDomain: 'mobileapp-project-d7c42.firebaseapp.com',
    storageBucket: 'mobileapp-project-d7c42.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvJI5hSHemb2GdvfbMvW43Y0Mr3GJUVu8',
    appId: '1:177508526111:android:484ebe123f30d0c3eecd2a',
    messagingSenderId: '177508526111',
    projectId: 'mobileapp-project-d7c42',
    storageBucket: 'mobileapp-project-d7c42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYPrjHcF56t-QtnwhTg-aH7KY6JeNsgos',
    appId: '1:177508526111:ios:a9ef326e438e9a47eecd2a',
    messagingSenderId: '177508526111',
    projectId: 'mobileapp-project-d7c42',
    storageBucket: 'mobileapp-project-d7c42.appspot.com',
    iosClientId: '177508526111-q55u4oeod630vbkob406l57qm2hn90h1.apps.googleusercontent.com',
    iosBundleId: 'com.example.project221000090',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYPrjHcF56t-QtnwhTg-aH7KY6JeNsgos',
    appId: '1:177508526111:ios:a9ef326e438e9a47eecd2a',
    messagingSenderId: '177508526111',
    projectId: 'mobileapp-project-d7c42',
    storageBucket: 'mobileapp-project-d7c42.appspot.com',
    iosClientId: '177508526111-q55u4oeod630vbkob406l57qm2hn90h1.apps.googleusercontent.com',
    iosBundleId: 'com.example.project221000090',
  );
}
